@startuml

title __DATABASE's Class Diagram__\n

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbHelper {
          {static} - DB_NAME : String
          {static} - VERSION : int
          + DbHelper()
          + onCreate()
          + onUpgrade()
      }
    }
  }
  

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbManager {
          - context : Context
          + DbManager()
          + countQuery()
          + countQueryWLElements()
          + getCountWishListsByValidity()
          + getEntriesDataQuery()
          + getRecentItemsQuery()
          + getWishListDataQuery()
          + getWishListsItems()
          + insertCategories()
          + insertIncome()
          + insertItems()
          + insertPurchaseSimple()
          + insertPurchases()
          + insertUser()
          + insertWishLists()
          + queryCheckUserLogin()
          + queryGetAllRows()
          + queryGetUserTotal()
          + sumIncomesQuery()
          + sumPurchasesQuery()
          + updateItemsValidity()
          + updateUserTotal()
          + updateWishListsValidity()
      }
    }
  }
  


  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbStrings.TableCategoriesFields {
          {static} + CATEGORIES_DESC : String
          {static} + CATEGORIES_ID : String
          {static} + CATEGORIES_PIC_ID : String
          {static} + TABLE_NAME : String
          {static} - CREATE_TABLE : String
          {static} ~ getCreateTable()
      }
    }
  }
  

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbStrings.TableIncomesFields {
          {static} + INCOMES_DATE : String
          {static} + INCOMES_ID : String
          {static} + INCOMES_ID_CAT : String
          {static} + INCOMES_ID_USER : String
          {static} + INCOMES_VAL : String
          {static} + TABLE_NAME : String
          {static} - CREATE_TABLE : String
          {static} ~ getCreateTable()
      }
    }
  }
  

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbStrings.TableItemsFields {
          {static} + ITEMS_AMOUNT : String
          {static} + ITEMS_ID : String
          {static} + ITEMS_ID_CAT : String
          {static} + ITEMS_NAME : String
          {static} + ITEMS_PRICE : String
          {static} + ITEMS_VALID : String
          {static} + TABLE_NAME : String
          {static} - CREATE_TABLE : String
          {static} ~ getCreateTable()
      }
    }
  }
  

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbStrings.TablePurchasesFields {
          {static} + PURCH_DATE : String
          {static} + PURCH_ID : String
          {static} + PURCH_ID_USER : String
          {static} + PURCH_ITEM_ID : String
          {static} + PURCH_TIME : String
          {static} + PURCH_WL_ID : String
          {static} + TABLE_NAME : String
          {static} ~ CREATE_TABLE : String
          {static} ~ getCreateTable()
      }
    }
  }
  

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbStrings.TableUsersField {
          {static} + TABLE_NAME : String
          {static} + USERS_EMAIL : String
          {static} + USERS_ID : String
          {static} + USERS_NAME : String
          {static} + USERS_PWD : String
          {static} + USERS_SURNAME : String
          {static} + USERS_TOT : String
          {static} - CREATE_TABLE : String
          {static} ~ getCreateTable()
      }
    }
  }
  

  namespace com.example.keepmoneyv3 {
    namespace database {
      class com.example.keepmoneyv3.database.DbStrings.TableWishListsFields {
          {static} + TABLE_NAME : String
          {static} + WL_DESC : String
          {static} + WL_ID : String
          {static} + WL_NAME : String
          {static} + WL_VALID : String
          {static} ~ CREATE_TABLE : String
          {static} ~ getCreateTable()
      }
    }
  }


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
